### ISSUE TITLE
syncthing-gtk needs to depend on python-gobject

### ISSUE THREAD

**Issue by pharpend** [UnitedRPMs/unitedrpms.github.io#7]
If you install `syncthing-gtk` without `python-gobject` also being installed, running `syncthing-gtk` in the command line will complain about the `gi` module not existing. From Googling, the solution is to install `python-gobject`. That fixed my issue.

**Comment by paulcarroty** [comment]
@pharpend fixed in new version, thanks.

**Comment by vontrapp** [comment]
there is no python-gobject package in centos. However, there is a pygobject4 package. pygobject3 provides the python gi module.

I'm guessing pharpend is using ubuntu perhaps, or at least not centos. RPM does a pretty good job of auto requiring python modules and so might not have been broken in the first place. Having the rpm depend on the 'python-gobject' package name makes it not install because it cannot meet that dependency.

**Comment by paulcarroty** [comment]
@vontrapp 

```
# dnf install python-gobject
Last metadata expiration check: 3:35:39 ago on Thu Dec 15 19:31:20 2016 EET.
Package python-gobject-3.22.0-1.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

```

**Comment by vontrapp** [comment]
I'm on centos, not fedora. Yum provides gives this:

pygobject3-base-3.14.0-3.el7.x86_64 : Python 2 bindings for GObject Introspection base package
Repo        : base
Matched from:
Filename    : /usr/lib64/python2.7/site-packages/gi/__init__.py

There's nothing for python-gobject.

**Comment by kuboosoft** [comment]
@vontrapp Sorry but UnitedRPMs no support Centos...
