### ISSUE TITLE
steam client is absent in Fedora 25 repo

### ISSUE THREAD

**Issue by NTMan** [UnitedRPMs/unitedrpms.github.io#8]
steam client is absent in Fedora 25 repo

**Comment by paulcarroty** [comment]
Fixed.

**Comment by NTMan** [comment]
![screenshot from 2016-09-16 02-05-19](https://cloud.githubusercontent.com/assets/200750/18567655/a1dc7db6-7bb2-11e6-88f0-5c10a1ce0680.png)

it's normal that package have suffix fc26?

**Comment by paulcarroty** [comment]
Yes.

**Comment by macktab** [comment]
I think, NTman mean, that this steam packet is from future.... Or we stick in the past and still using old fedora 25 alpha.

**Comment by paulcarroty** [comment]
@NTMan @macktab It's good that you're interested, guys. Let's explain the Fedora releases - https://fedoraproject.org/wiki/Releases

* F26 (now Rawhide) - a test release ("master") - it's [alive](https://www.happyassassin.net/nightlies.html).
* F25 - now alpha release
* F24 - stable release. 

After some time we'll have a +1 switch - rawhide - F27, alpha - F26 (branched from rawhide), stable - F25.

We had a problem with F25 Copr builder and used F26 for build the F25 packages - that you can see `fc26` packages in F25. F26 & F26 now have a minimal difference because the both isn't stabilized and you have no reason to worry about it.
